#  Command Blocker Ultimate config file
#  Get help at https://github.com/xxyy/commandblockerultimate/issues

# Define what commands should be blocked in the following property: (without leading slash)
# If you specify a command, its aliases will be blocked also. (Example: 'tell' will also block 'msg', 'bukkit:tell', etc.)
target-commands:
 - help
 - plugins
 - version

# Define the permission that a player needs to bypass the protection:
bypass-permission: cmdblock.bypass

# Should the plugin send an error message if one is not allowed to execute a command?
show-error-message: true

# What should that message be? (Use & for color codes, HTML escape codes accepted)
# <command> will be replaced with the blocked command's name
# Example: &c&lError message &euro;&auml;&#00A7;
error-message: '&cI am sorry, but you are not permitted to execute this command.'

# @since 1.02
# Whether to prevent tab-completion for blocked commands.
# Note: Requires ProtocolLib!
# Default value: true
prevent-tab: true

# What strategy to use when blocking tab-complete replies from the server.
# true: block all completions returning a targeted command (for example, if /p is typed and /pl is blocked, print error message)
# false: just remove blocked commands from list (in the above example, other commands starting with p would still be shown without notice)
# Default value: false
tab-restrictive-mode: false

# @since 1.4.0
# Whether to display a message when executing an otherwise blocked command to permitted users
# Default value: false
notify-bypass: false

# @since 1.4.0
# The message to display when executing an otherwise blocked command (permitted users only, see notify-bypass)
# <command> will be replaced with the blocked command's name
# Example: '&c/<command> is blocked. Executing anyways since you have permission.'
bypass-message: '&c[CBU] /<command> is blocked. Executing anyways since you have permission.'

# @since 1.4.0
# The message to display when somebody tries to tab-complete a command that's blocked and
# tab-restrictive-mode is enabled.
# Example: '&cI am sorry, but you cannot see completions for this.'
tab-error-message: '&cI am sorry, but I cannot let you do this, Dave.'
