#  Command Blocker Ultimate config file

# Define what commands should be blocked in the following property: (without leading slash)
target-commands:
 - "?"
 - help
 - plugins
 - pl
 - version
 - ver
 - about

# Define the permission that a player needs to bypass the protection:
bypass-permission: cmdblock.bypass

# Should the plugin send an error message if one is not allowed to execute a command?
show-error-message: true

# What should that message be? (Use & for color codes, HTML escape codes accepted)
# Example: &c&lError message &euro;&auml;&#00A7;
error-message: '&cI am sorry, but you are not permitted to execute this command.'

# @since 1.02
# Whether to prevent tab-completion for blocked commands.
# Note: Requires ProtocolLib!
# Default value: true
prevent-tab: true

# What strategy to use when blocking tab-complete replies from the server.
# true: block all completions returning a targeted command (for example, if /p is typed and /pl is blocked, print error message)
# false: just remove blocked commands from list (in the above example, other commands starting with p would still be shown without notice)
# Default value: false
tab-restrictive-mode: false
